# GitHub Action for Laravel with MySQL and Redis
name: Purge JSDelivr cache
on: [push, pull_request]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Purge JSDelivr CSS
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://purge.jsdelivr.net/gh/4site-interactive-studios/${{ github.event.repository.name }}@${{ github.head_ref || github.ref_name }}/dist/engrid.css'
        method: 'GET'
    - name: Purge JSDelivr JS
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://purge.jsdelivr.net/gh/4site-interactive-studios/${{ github.event.repository.name }}@${{ github.head_ref || github.ref_name }}/dist/engrid.js'
        method: 'GET'
    - name: Debug
      run: |
          echo "The repo name is: ${{ github.event.repository.name }}" 
          echo "The branch name is: ${{ github.head_ref || github.ref_name }}" 